copied changes from old repo
DistributedCollective/babelfish-sc pull request #1
Opened 2023-12-19 09:28 UTC by dharkmattr

2023-12-22 00:02 UTC, tjcloa requested changes
1) fix a failing CI check
2) pls restructure the repo to comply with Sovryn structure if no objections: rename `main` to `development` branch and create `main` branch used as target for versioning and immunify bug bounty programs
3) address inline comments

2023-12-22 00:02 UTC, tjcloa commented on contracts/masset/Masset.sol
> +        require(msg.sender == adminMultisig, "not allowed");
i recommend to add requirement tokenA != tokenB

2023-12-22 00:02 UTC, tjcloa commented on test/TestMasset.spec.ts
missing tests for `Masset.convertTokens(...)`

2023-12-22 10:58 UTC, tjcloa approved these changes

2023-12-22 11:25 UTC, tjcloa approved these changes

2024-01-02 07:46 UTC, koirikivi commented on contracts/masset/Masset.sol
> +    function convertTokens(address _tokenA, address _tokenB, uint256 _amount) public {
- This is not non-reentrant. Whether it matters or not, I don't know.
- Why public and not external?

2024-01-02 07:48 UTC, koirikivi approved these changes
LGTM, but added one review comment nevertheless.

2024-01-08 11:35 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +    function convertTokens(address _tokenA, address _tokenB, uint256 _amount) public {
will change to external

2024-01-08 11:37 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +    function convertTokens(address _tokenA, address _tokenB, uint256 _amount) public {
what do you mean by non-reentrant? It can only be called by the MS

2024-01-10 13:34 UTC, koirikivi approved these changes

2024-01-16 07:08 UTC, merged